// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: go_api_enum.proto

package apiflagdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoAPI int32

const (
	GoAPI_GO_API_UNSPECIFIED    GoAPI = 0
	GoAPI_INVALID               GoAPI = 1
	GoAPI_OPEN_V1               GoAPI = 2
	GoAPI_OPEN_TO_OPAQUE_HYBRID GoAPI = 3
	GoAPI_OPAQUE_V0             GoAPI = 4
)

// Enum value maps for GoAPI.
var (
	GoAPI_name = map[int32]string{
		0: "GO_API_UNSPECIFIED",
		1: "INVALID",
		2: "OPEN_V1",
		3: "OPEN_TO_OPAQUE_HYBRID",
		4: "OPAQUE_V0",
	}
	GoAPI_value = map[string]int32{
		"GO_API_UNSPECIFIED":    0,
		"INVALID":               1,
		"OPEN_V1":               2,
		"OPEN_TO_OPAQUE_HYBRID": 3,
		"OPAQUE_V0":             4,
	}
)

func (x GoAPI) Enum() *GoAPI {
	p := new(GoAPI)
	*p = x
	return p
}

func (x GoAPI) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoAPI) Descriptor() protoreflect.EnumDescriptor {
	return file_go_api_enum_proto_enumTypes[0].Descriptor()
}

func (GoAPI) Type() protoreflect.EnumType {
	return &file_go_api_enum_proto_enumTypes[0]
}

func (x GoAPI) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoAPI.Descriptor instead.
func (GoAPI) EnumDescriptor() ([]byte, []int) {
	return file_go_api_enum_proto_rawDescGZIP(), []int{0}
}

var File_go_api_enum_proto protoreflect.FileDescriptor

const file_go_api_enum_proto_rawDesc = "" +
	"\n" +
	"\x11go_api_enum.proto\x12%net.proto2.go.open2opaque.apiflagdata*i\n" +
	"\x05GoAPI\x12\x16\n" +
	"\x12GO_API_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aINVALID\x10\x01\x12\v\n" +
	"\aOPEN_V1\x10\x02\x12\x19\n" +
	"\x15OPEN_TO_OPAQUE_HYBRID\x10\x03\x12\r\n" +
	"\tOPAQUE_V0\x10\x04\"\x04\b\x05\x10\x05b\beditionsp\xe8\a"

var (
	file_go_api_enum_proto_rawDescOnce sync.Once
	file_go_api_enum_proto_rawDescData []byte
)

func file_go_api_enum_proto_rawDescGZIP() []byte {
	file_go_api_enum_proto_rawDescOnce.Do(func() {
		file_go_api_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_api_enum_proto_rawDesc), len(file_go_api_enum_proto_rawDesc)))
	})
	return file_go_api_enum_proto_rawDescData
}

var file_go_api_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_go_api_enum_proto_goTypes = []any{
	(GoAPI)(0), // 0: net.proto2.go.open2opaque.apiflagdata.GoAPI
}
var file_go_api_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_go_api_enum_proto_init() }
func file_go_api_enum_proto_init() {
	if File_go_api_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_api_enum_proto_rawDesc), len(file_go_api_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_api_enum_proto_goTypes,
		DependencyIndexes: file_go_api_enum_proto_depIdxs,
		EnumInfos:         file_go_api_enum_proto_enumTypes,
	}.Build()
	File_go_api_enum_proto = out.File
	file_go_api_enum_proto_goTypes = nil
	file_go_api_enum_proto_depIdxs = nil
}
